=== morandat/tima/src/main/resources/fr/labri/tima/tima.xsd
<xs:schema xmlns:xs='http://www.w3.org/2001/XMLSchema' xmlns="http://se.labri.fr/tima" targetNamespace="http://se.labri.fr/tima">
	<xs:element name='timedautomata'>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref='state' minOccurs='0' maxOccurs='unbounded' />
				<xs:element ref='timedautomata' minOccurs='0' maxOccurs='unbounded' />
			</xs:sequence>
			<xs:attribute name='name' type='xs:ID' use='required' />
		</xs:complexType>
	</xs:element>

	<xs:element name='state'>
		<xs:complexType>
			<xs:sequence>
				<xs:element ref='path' minOccurs='0' maxOccurs='unbounded' />
				<xs:element ref='default' minOccurs='0' maxOccurs='1' />
				<xs:element ref='action' minOccurs='0' maxOccurs='unbounded' />
				<xs:element ref='terminate' minOccurs='0' maxOccurs='1' />
			</xs:sequence>
			<xs:attribute name='name' type='xs:ID' use='required' />
			<xs:attribute name='action' type='xs:string' use='optional' />
			<xs:attribute name='initial' use='optional' />
			<xs:attribute name='terminal' use='optional'>
				<xs:simpleType>
					<xs:restriction base='xs:string'>
						<xs:enumeration value='true' />
						<xs:enumeration value='false' />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
			<xs:attribute name='urgent' use='optional'>
				<xs:simpleType>
					<xs:restriction base='xs:string'>
						<xs:enumeration value='true' />
						<xs:enumeration value='false' />
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>

	<xs:element name='path'>
		<xs:complexType>
			<xs:attribute name='to' type='xs:string' use='required' />
			<xs:attribute name='guard' type='xs:string' use='required' />
			<xs:attribute name='timeout' type='xs:string' use='optional' />
			<xs:attribute name='attr' type='xs:string' use='optional' />
		</xs:complexType>
	</xs:element>

	<xs:element name='action'>
		<xs:complexType>
			<xs:attribute name='type' type='xs:string' use='required' />
			<xs:attribute name='attr' type='xs:string' use='optional' />
		</xs:complexType>
	</xs:element>

	<xs:element name='terminate' />

	<xs:element name='default'>
		<xs:complexType>
			<xs:attribute name='to' type='xs:string' use='required' />
		</xs:complexType>
	</xs:element>
</xs:schema>

=== morandat/tima/src/test/resources/ex1.xml
<?xml version="1.0" encoding="UTF-8"?>
<timedautomata xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
               xsi:noNamespaceSchemaLocation="http://www.labri.fr/~fmoranda/xsd/tima.xsd"
               name="ex1">

    <state name="s0" action="s0" initial="true">
        <path to="s1" timeout="10" guard="t1"/>
        <path to="s2" timeout="15" guard="t2"/>
        <timeout to="timeout"/>
    </state>
    <state name="s2" action="s2">
        <path to="s3" timeout="10" guard="t3"/>
        <timeout to="timeout"/>
    </state>
    <state name="s1" action="s1">
        <path to="s2" timeout="12" guard="t4"/>
        <timeout to="timeout"/>
    </state>
    <state name="s3" action="s3">
        <path to="s1" timeout="5" guard="t5"/>
        <timeout to="timeout"/>
    </state>
    <state name="timeout" action="timeout"/>
</timedautomata>
